### ISSUE TITLE
Crocks filled with a mix of 2 servings from one cooking pot and 2 servings from another has incorrect hydration value

### ISSUE THREAD

**Issue by Mohaim-1** [Chronolegionnaire/HydrateOrDiedrate#16]
### How I encountered the bug:

I made two cooking pots of identical soup. I then filled one crock with 4 servings from the first pot, then with a second crock took the remaining 2 servings from the first pot and 2 servings from the second pot, then with a third crock took the final 4 servings from the second pot. The first crock had 163 hydration, the second crock had 326 (2x) hydration, and the third crock had 0 hydration.

![Screenshot_20240825_214307](https://github.com/user-attachments/assets/f2ee4d16-dd0d-477d-8b45-ecc600797ef5)
![Screenshot_20240825_214314](https://github.com/user-attachments/assets/36e7d3a1-f143-4879-8ebd-035ea94775b6)
![Screenshot_20240825_214329](https://github.com/user-attachments/assets/dbda90e9-09f9-407a-82dc-9c0177dd9b73)

### How it should work:

All three crocks should have the same amount of hydration (in this case, 163) since they are filled with the same food.

### Save file

https://drive.google.com/file/d/1673TpzNXR_fe62grDdfBcCTeWEp8J100/edit (716 MB)

### Installed Mods

ACulinaryArtillery 1.1.5.zip
alchemistry-1.0.2.zip
alchemy_1.6.35.zip
animationmanagerlib_0.8.8.zip
autoatlas-1.0.1.zip
Auto Map Markers (1.19).zip
AWearableLight-v1.1.1.zip
BackpackPackStandard_v1.0.3.zip
beehivekiln_1.6.1.zip
BeltCraft.zip
bodyheatbarfixed.zip
bricklayers-2.5.6.zip
Bullseye_2.5.8.zip
butchering_1.6.6.zip
CaptureAnimals_VS1.19.7_net7_v2.7.0.zip
CarryOn-1.19_v1.7.4.zip
chemistrylib-1.1.5.zip
clipfix-1.19.7-2.0.2.zip
CommonLib_VS1.19.8_net7_v2.5.0-rc.2.zip
configlib_1.3.13.zip
DanaTweaks-v3.1.0.zip
displaycasewall_1.0.3.zip
DoffAndDonAgain_v4.0.0.zip
drbraziers_1.1.1.zip
dressmakers-1.4.0.zip
Eldritch'sCuteClothing-1.0.2.zip
ExpandedFoods 1.7.0.zip
expanded_matter-2.7.0.zip
foodshelves_1.1.4.zip
HideAndFabric-1.3.0.zip
hideplayername_2.0.6.zip
hit_2.1.1.zip
hudclock-3.4.0.zip
hydrateordiedrate_1.2.1.zip
immersivetpscamera_1.0.5.zip
InDappledGroves-1.19-v0.8.3.zip
instantDrifterDrops_v1.1.0.zip
kiln-time-viewer-v1.0.1.zip
kosphotography_1.4.3.zip
lavoisier-1.3.0.zip
LiquidContainers-1.2.0.zip
Mannequin-Stand-v1.0.3.zip
MeteoricExpansion_V1.2.5.zip
mif_1.0.0.zip
millwright_1.1.6.zip
nohands-0.1.1.zip
particlesplus_v1.1.0.zip
pelaguswinds_1.0.0.zip
pickupartist-0.2.0.zip
PlayerCorpse_VS1.19.0-rc.5_net7_v1.9.0.zip
pomnotes_v0.7.1.zip
pretzels-1.0.1.zip
primitivesurvival_3.5.7.zip
ProspectTogether-1.3.0.zip
RecipePatcher-v1.1.1.zip
rivers_3.1.0.zip
sailboat_1.3.1.zip
SimpleCloth_v1.0.2.zip
simplefootstepsredux.zip
spawnhighlight_1.2.0.zip
StorageOptions-v1.0.2.zip
SuperFuelResumed-v2.1.3.zip
tailors_delight-1.6.0.zip
toolworks_1.8.1.zip
toolworksadditions_1.3.2.zip
TrapDoorsAreLadders_v1.0.0.zip
TypingIndicator.zip
upholstery-1.0.1.zip
VanillaVariants-v5.0.3.zip
Vanity-2.2.0.zip
vintage_recipes-1.2.2.zip
VolumetricShadingReUpdated_v0.7.5.zip
vsimgui_1.1.5.zip
wildfarmingrevival_1.2.4.zip
xinvtweaks_v1.6.6.zip
zoombuttonreborn_1.8.0.zip

**Comment by Chronolegionnaire** [comment]
Looking into this now, I think it may be a mod incompatibility, doing more testing now

**Comment by Chronolegionnaire** [comment]
Disregard that, just reproduced it

**Comment by Chronolegionnaire** [comment]
Fixed in latest versions!
